
import java.awt.Font;

/*
 * NewJFrame.java
 *
 * Created on 16 Desember 2021, 11:20
 */
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;



/**
 *
 * @author  helnat
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NamaLabel = new javax.swing.JLabel();
        NamaTF = new javax.swing.JTextField();
        AlamatLabel = new javax.swing.JLabel();
        AlamatTF = new javax.swing.JTextField();
        PekerjaanLabel = new javax.swing.JLabel();
        PekerjaanCB = new javax.swing.JComboBox();
        JenisKelaminCB = new javax.swing.JComboBox();
        JeniskelaminLabel = new javax.swing.JLabel();
        JeniscetakLabel = new javax.swing.JLabel();
        TebalCB = new javax.swing.JComboBox();
        TampilkanBT = new javax.swing.JButton();
        HapusBT = new javax.swing.JButton();
        SimpanBT = new javax.swing.JButton();
        ExitBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NamaLabel.setText("Nama");

        AlamatLabel.setText("Alamat");

        PekerjaanLabel.setText("Pekerjaan");

        PekerjaanCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PNS", "TNI", "Karyawan", "Pengusaha" }));
        PekerjaanCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PekerjaanCBActionPerformed(evt);
            }
        });

        JenisKelaminCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));

        JeniskelaminLabel.setText("Jenis Kelamin");

        JeniscetakLabel.setText("Jenis Cetak");

        TebalCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tebal", "Miring" }));

        TampilkanBT.setText("Tampilkan");
        TampilkanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkanBTActionPerformed(evt);
            }
        });

        HapusBT.setText("Hapus");
        HapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBTActionPerformed(evt);
            }
        });

        SimpanBT.setText("Simpan");
        SimpanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanBTActionPerformed(evt);
            }
        });

        ExitBT.setText("Exit");
        ExitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JeniscetakLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PekerjaanLabel)
                                    .addComponent(JeniskelaminLabel)
                                    .addComponent(NamaLabel)
                                    .addComponent(AlamatLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AlamatTF)
                                    .addComponent(NamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PekerjaanCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TebalCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JenisKelaminCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TampilkanBT)
                        .addGap(18, 18, 18)
                        .addComponent(HapusBT)
                        .addGap(18, 18, 18)
                        .addComponent(SimpanBT)
                        .addGap(18, 18, 18)
                        .addComponent(ExitBT)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaLabel)
                    .addComponent(NamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlamatLabel)
                    .addComponent(AlamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PekerjaanLabel)
                    .addComponent(PekerjaanCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JenisKelaminCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JeniskelaminLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JeniscetakLabel)
                    .addComponent(TebalCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TampilkanBT)
                    .addComponent(HapusBT)
                    .addComponent(SimpanBT)
                    .addComponent(ExitBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void PekerjaanCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PekerjaanCBActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_PekerjaanCBActionPerformed

private void TampilkanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkanBTActionPerformed
// TODO add your handling code here:
//mengambil nilai dari textfield nama dan alamat
    String nama = NamaTF.getText();
    String alamat = AlamatTF.getText();
    //mengambil nilai dari combobox pekerjaan, jenis kelamin, dan jenis cetak
    String pekerjaan = (String) PekerjaanCB.getSelectedItem();
    String jeniskelamin = (String) JenisKelaminCB.getSelectedItem();
    String jeniscetak = (String) TebalCB.getSelectedItem();
    //buat fngsi font
    Font tebal = new Font ("Arial", Font.BOLD, 12);
    Font miring = new Font ("Arial", Font.ITALIC,12);
    //set hasil efek font ke text area
    if (jeniscetak == "Tebal"){
        jTextArea1.setFont(tebal);
    }
    if (jeniscetak == "Miring"){
        jTextArea1.setFont(miring);
    }
    
    jTextArea1.setText ("Nama Saya" + nama + " \n alamat saya tinggal " + alamat + " \n dengan pekerjaan " +  pekerjaan + "\n jenis kelamin saya " + jeniskelamin);
    
}//GEN-LAST:event_TampilkanBTActionPerformed

private void SimpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanBTActionPerformed
// TODO add your handling code here:
        try{
        //buatfile
        BufferedWriter out = new BufferedWriter(new FileWriter("Penyimpanan.txt"));
        //simpan ke file
        out.write(jTextArea1.getText());
        //tampilan dialog telah berhasil
        JOptionPane.showMessageDialog(null, "Berhasil disimpan ke dalam file");
        //tutup output stream
        out.close();
        
    }catch(Exception e){
        System.err.println("Error :" + e.getMessage());
    }
}//GEN-LAST:event_SimpanBTActionPerformed

private void ExitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_ExitBTActionPerformed

private void HapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBTActionPerformed
// TODO add your handling code here:
    NamaTF.setText("");
    AlamatTF.setText("");
    JenisKelaminCB.setSelectedItem("Laki-Laki");
    PekerjaanCB.setSelectedItem("PNS");
    TebalCB.setSelectedItem("Tebal");
    jTextArea1.setText("");
}//GEN-LAST:event_HapusBTActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatLabel;
    private javax.swing.JTextField AlamatTF;
    private javax.swing.JButton ExitBT;
    private javax.swing.JButton HapusBT;
    private javax.swing.JComboBox JenisKelaminCB;
    private javax.swing.JLabel JeniscetakLabel;
    private javax.swing.JLabel JeniskelaminLabel;
    private javax.swing.JLabel NamaLabel;
    private javax.swing.JTextField NamaTF;
    private javax.swing.JComboBox PekerjaanCB;
    private javax.swing.JLabel PekerjaanLabel;
    private javax.swing.JButton SimpanBT;
    private javax.swing.JButton TampilkanBT;
    private javax.swing.JComboBox TebalCB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
